### ISSUE TITLE
open to a refactor pr?

### ISSUE THREAD

**Issue by jonschlinkert** [js-cli/node-findup-sync#15]
I created [this lib](https://github.com/jonschlinkert/look-up/blob/master/index.js) as an attempt to implement a faster implementation, but I didn't want to do a pr until I spent some time actually using it in applications etc. 

I took a different approach than what this does currently, so to be honest it's possible I'm missing some nuances about the current implementation. (edit: although I _think_ it covers all the bases. the unit tests have the same coverage, etc).

I'd be happy to move the code here, and just deprecate my repo - I've used this lib quite a bit in projects it's the least I can do.  Just let me know whatever code changes might need to be made, etc.  If not, no worries at all

**Comment by tkellen** [comment]
@jonschlinkert still thinking of doing this?

**Comment by jonschlinkert** [comment]
@tkellen I'd like to, still waiting for a code review :)

**Comment by jonschlinkert** [comment]
funny, I just realized that I didn't do an actual PR! I'll get one sent over so you can review properly

**Comment by tkellen** [comment]
:D

**Comment by jonschlinkert** [comment]
I haven't forgotten about this, I found a bug in minimatch and want to make sure there are no other issues before I do a PR. I should have something pushed up in the next couple of days.

**Comment by jonschlinkert** [comment]
k, I pushed up some updates to lookup. @tkellen / @cowboy are you guys okay with me keeping the tests, docs, etc as they are in look-up? I don't mind converting stuff, it will just take a little longer. So I guess I'm asking if you are cool with me gutting the project lol.

also, I got rid of minimatch in favor of micromatch. It solved it at least one matching bug I found, and the it's considerable faster as well.  Here are the new benchmarks: https://github.com/jonschlinkert/look-up#running-benchmarks.

**Comment by tkellen** [comment]
Gut away @jonschlinkert !

**Comment by jonschlinkert** [comment]
see https://github.com/cowboy/node-findup-sync/pull/16

**Comment by jonschlinkert** [comment]
btw, when I created this I tested on both windows and mac, but my windows machine died and I've made changes since then. I'd love for someone else to verify that it's working as expected on windows.

**Comment by tkellen** [comment]
Heya @jonschlinkert!

Would you be willing to incorporate your changes here? I'd love to either update this library or deprecate it in favor of look-up. Also, @phated and I have moved all of our cli specific libraries to the `js-cli` organization. Would you be interested in doing the same for yours so we can collectively ensure a good future for our efforts?

**Comment by jonschlinkert** [comment]
thanks for the reminder! sure I'll just move those changes here and deprecate look-up.  I can move other libs here too, any specifically that you think make sense?

**Comment by phated** [comment]
@jonschlinkert I just invited you to the js-cli org

**Comment by jonschlinkert** [comment]
accepted, thank you. 

btw I should mention it might be a few days before I can get this updated, but I made a note of it so it's on my priority list!
