### ISSUE TITLE
Dependency on deprecated module

### ISSUE THREAD

**Issue by Lucretiel** [js-cli/node-findup-sync#35]
This module has the dependency chain node-findup-sync => findup-sync@0.2.1 => glob@4.3.5 => minimatch@2.0.10. minimatch@2.0.10 is deprecated, and npm reports a potential security hole. If possible, please update the dependency to the latest version of findup-sync (0.4.1), which doesn't have this issue.

**Comment by jonschlinkert** [comment]
this is findup-sync, which no longer uses minimatch

**Comment by Lucretiel** [comment]
Ah, I see. Do you know if findup-sync 0.4.1 has API compatibility with 0.2.1?
