### ISSUE TITLE
Need to update dependencies (especially ones below 1.0)

### ISSUE THREAD

**Issue by phated** [js-cli/node-findup-sync#41]
I'm reviewing gulp deps and just noticed this.

**Comment by jonschlinkert** [comment]
we should remove `fs-exists-sync` and just use `fs.existsSync`. Initially I thought that was deprecated, but it's not now.

**Comment by phated** [comment]
@jonschlinkert
> Note that fs.exists() is deprecated, but fs.existsSync() is not. (The callback parameter to fs.exists() accepts parameters that are inconsistent with other Node.js callbacks. fs.existsSync() does not use a callback.)

Heh, what are they even doing 😭

**Comment by phated** [comment]
Just missing detect-file, I believe.

**Comment by phated** [comment]
Closed by 2.0.0
